/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'lms-darkest': '#0f172a',
        'lms-dark': '#1e293b',
        'lms-primary': '#3b82f6',
        'lms-accent': '#6366f1',
        'lms-warm': '#8b5cf6',
        'lms-muted': '#64748b',
        'lms-surface': '#f8fafc',
        'lms-border': '#e2e8f0',
        'lms-card': '#ffffff',
        'lms-text': '#1e293b',
        'lms-light': '#94a3b8',
        'lms-teal': '#14b8a6',
        'lms-rose': '#f43f5e',
        'lms-amber': '#f59e0b',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'floatSlow 8s ease-in-out infinite',
        'float-fast': 'floatFast 4s ease-in-out infinite',
        'float-delay': 'float 6s ease-in-out 2s infinite',
        'pulse-glow': 'pulseGlow 3s ease-in-out infinite',
        'pulse-glow-delay': 'pulseGlow 3s ease-in-out 1.5s infinite',
        'slide-up': 'slideUp 0.8s ease-out forwards',
        'slide-up-delay': 'slideUp 0.8s ease-out 0.3s forwards',
        'slide-up-delay2': 'slideUp 0.8s ease-out 0.6s forwards',
        'fade-in': 'fadeIn 1s ease-out forwards',
        'fade-in-delay': 'fadeIn 1s ease-out 0.4s forwards',
        'fade-in-delay2': 'fadeIn 1s ease-out 0.8s forwards',
        'spin-slow': 'spin 20s linear infinite',
        'spin-reverse': 'spin 25s linear infinite reverse',
        'orbit': 'orbit 15s linear infinite',
        'orbit-reverse': 'orbit 20s linear infinite reverse',
        'orbit-fast': 'orbit 10s linear infinite',
        'particle-1': 'particle1 12s ease-in-out infinite',
        'particle-2': 'particle2 15s ease-in-out infinite',
        'particle-3': 'particle3 10s ease-in-out infinite',
        'particle-4': 'particle4 18s ease-in-out infinite',
        'dash': 'dash 4s ease-in-out infinite',
        'dash-delay': 'dash 4s ease-in-out 1s infinite',
        'dash-delay2': 'dash 4s ease-in-out 2s infinite',
        'scale-pulse': 'scalePulse 4s ease-in-out infinite',
        'wiggle': 'wiggle 3s ease-in-out infinite',
        'morph': 'morph 8s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        floatSlow: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-30px) rotate(5deg)' },
        },
        floatFast: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '0.3', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.05)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        orbit: {
          '0%': { transform: 'rotate(0deg) translateX(100px) rotate(0deg)' },
          '100%': { transform: 'rotate(360deg) translateX(100px) rotate(-360deg)' },
        },
        particle1: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)', opacity: '0.4' },
          '25%': { transform: 'translate(80px, -40px) scale(1.3)', opacity: '0.7' },
          '50%': { transform: 'translate(40px, -80px) scale(0.8)', opacity: '0.5' },
          '75%': { transform: 'translate(-30px, -20px) scale(1.1)', opacity: '0.6' },
        },
        particle2: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)', opacity: '0.3' },
          '33%': { transform: 'translate(-60px, -50px) scale(1.4)', opacity: '0.7' },
          '66%': { transform: 'translate(50px, -70px) scale(0.6)', opacity: '0.4' },
        },
        particle3: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)', opacity: '0.5' },
          '50%': { transform: 'translate(-50px, 30px) scale(1.2)', opacity: '0.8' },
        },
        particle4: {
          '0%, 100%': { transform: 'translate(0, 0)', opacity: '0.2' },
          '30%': { transform: 'translate(70px, -60px)', opacity: '0.6' },
          '60%': { transform: 'translate(-40px, -90px)', opacity: '0.3' },
        },
        dash: {
          '0%': { strokeDashoffset: '1000', opacity: '0.1' },
          '50%': { strokeDashoffset: '0', opacity: '0.5' },
          '100%': { strokeDashoffset: '-1000', opacity: '0.1' },
        },
        scalePulse: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(3deg)' },
          '75%': { transform: 'rotate(-3deg)' },
        },
        morph: {
          '0%, 100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' },
          '25%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' },
          '50%': { borderRadius: '50% 60% 30% 70% / 40% 70% 50% 60%' },
          '75%': { borderRadius: '40% 30% 60% 50% / 70% 40% 60% 30%' },
        },
      },
    },
  },
  plugins: [],
  darkMode: 'class',
}
